[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tip_jar = "Gu7sMSSwiYm4JhKisQxAEA8EyJhiKfE2WRQuPFiUjinK"

# Add this block for devnet (placeholder for now)
[programs.devnet]
tip_jar = "Gu7sMSSwiYm4JhKisQxAEA8EyJhiKfE2WRQuPFiUjinK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"                    # <--- change from localnet to devnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
